apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

namespace: playground-staging

resources:
- ../../base

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-1c92daa
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-1c92daa

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-staging.substrate.dev
  target:
    group: extensions
    kind: Ingress
    name: ingress
    version: v1beta1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 34.69.4.59
- |-
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground-staging.substrate.dev'
      secretName: playground-tls
