name: Continuous Deployment Playground staging

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'templates/**'

env:
  GKE_CLUSTER: susbtrate-playground-staging
  GKE_ZONE: us-central1-a
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          # GCLOUD_KEY is the base64 of the gcloud service account JSON file
          # Get the JSON file from https://console.cloud.google.com/iam-admin/serviceaccounts?authuser=1&hl=fr&project=substrateplayground-252112&folder=&organizationId=&supportedpurview=project
          # ... -> Actions -> Create Key
          # then base64 substrateplayground-XXX.json | tr -d \\n
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - run: echo "::set-env name=ACCESS_TOKEN::$(gcloud auth print-access-token)"
      - uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
        with:
          username: oauth2accesstoken
          password: ${{ env.ACCESS_TOKEN }}
          path: backend
          dockerfile: backend/Dockerfile
          repository: substrateplayground-252112/jeluard/substrate-playground
          registry: gcr.io
          tags: latest
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.6.1/kustomize_v3.6.1_linux_amd64.tar.gz
          tar zxvf kustomize*
          chmod u+x ./kustomize  
        working-directory: conf/k8s/overlays/staging
      - name: Update version
        run: |-
          ./kustomize edit set image gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-api:sha-${GITHUB_SHA::7}
          ./kustomize edit set image gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-ui:sha-${GITHUB_SHA::7}
        working-directory: conf/k8s/overlays/staging
      - uses: EndBug/add-and-commit@v4
        with:
          message: "Update images versions"
          add: "conf/k8s/overlays/staging/kustomization.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          dry_run: true
#      - name: Commit and push files
#        run: |
#          set -x
#          cd "${GITHUB_WORKSPACE}"
#          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#          git config user.name "${GITHUB_ACTOR}"
#          git config --local --unset-all "http.https://github.com/.extraheader"
#          git remote add github "https://${GITHUB_ACTOR}:${PERSONAL_ACCESS_TOKEN}@github.com/paritytech/substrate-playground.git"
#          git pull github develop --ff-only
#          git add conf/k8s/overlays/staging/kustomization.yaml
#          git config --list
#          git commit -m "ci: Updated playground image"
#          git push github HEAD:develop --follow-tags
#        env:
#          PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          branch: develop
#          github_token: ${{ secrets.PAT_TOKEN }}
      - name: Deploy on GKE
        run:  |-
          ./kustomize build . | kubectl apply --record -f -
          kubectl get services -o wide
        working-directory: conf/k8s/overlays/staging